CREATE OR REPLACE TRIGGER InsertionAdherent
BEFORE INSERT ON Adherent
FOR EACH ROW
BEGIN
  IF :NEW.Num_Adherent IS NULL THEN
    SELECT SEQ_ADHERENT.nextval INTO :NEW.Num_Adherent FROM DUAL;
  END IF;
END;